/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IronLockFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ANTI_SNIPE_MAX_BNB"
      | "ANTI_SNIPE_SECONDS"
      | "DAILY_SELL_CAP_BPS"
      | "DEV_STAKE_AMOUNT"
      | "ELIGIBILITY_PROOF_TTL"
      | "MAX_DEV_BPS"
      | "MIN_LP_LOCK_DAYS"
      | "MIN_UNIQUE_CONTRIBUTORS"
      | "MIN_VESTING_DAYS"
      | "REPORT_THRESHOLD"
      | "allTokens"
      | "antiSnipeContribs"
      | "blacklistWallet"
      | "castRefundVote"
      | "checkLaunchSuccess"
      | "claimDevStake"
      | "claimRefund"
      | "contribute"
      | "contributions"
      | "devLastActivity"
      | "devLaunchHistory"
      | "devRefundedLaunches"
      | "devStakes"
      | "devSuccessfulLaunches"
      | "executeRefund"
      | "getAllTokens"
      | "getDevLaunchHistory"
      | "getDevStats"
      | "getSafetyScore"
      | "getTokensPaginated"
      | "hasContributed"
      | "hasReported"
      | "insurancePool"
      | "isBlacklisted"
      | "isBlockedContributor"
      | "isIronLockToken"
      | "isRefundVotePassed"
      | "launchFee"
      | "launchToken"
      | "owner"
      | "refundVotes"
      | "releaseMilestone"
      | "renounceOwnership"
      | "reportSuspiciousWallet"
      | "setLaunchFee"
      | "setTreasury"
      | "setVerifier"
      | "startRefundVote"
      | "suspiciousReportCount"
      | "tokenCount"
      | "tokens"
      | "transferOwnership"
      | "treasury"
      | "unblacklistWallet"
      | "updateDevActivity"
      | "usedEligibilityProofs"
      | "verifier"
      | "withdrawStuckBNB"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BlacklistAdded"
      | "Contributed"
      | "DevActivityUpdated"
      | "DevReputationUpdated"
      | "DevStakeClaimed"
      | "DevStakeSlashed"
      | "LaunchFeeUpdated"
      | "MilestoneReleased"
      | "OwnershipTransferred"
      | "RefundExecuted"
      | "RefundVoteCast"
      | "RefundVoteStarted"
      | "StuckBNBWithdrawn"
      | "TokenLaunched"
      | "TreasuryUpdated"
      | "VerifierUpdated"
      | "WalletBlocked"
      | "WalletReported"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ANTI_SNIPE_MAX_BNB",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ANTI_SNIPE_SECONDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DAILY_SELL_CAP_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEV_STAKE_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ELIGIBILITY_PROOF_TTL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_DEV_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_LP_LOCK_DAYS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_UNIQUE_CONTRIBUTORS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_VESTING_DAYS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REPORT_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "antiSnipeContribs",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistWallet",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "castRefundVote",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "checkLaunchSuccess",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimDevStake",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "contribute",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "contributions",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "devLastActivity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "devLaunchHistory",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "devRefundedLaunches",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "devStakes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "devSuccessfulLaunches",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeRefund",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDevLaunchHistory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDevStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSafetyScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokensPaginated",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasContributed",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasReported",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "insurancePool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isBlacklisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isBlockedContributor",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isIronLockToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRefundVotePassed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "launchFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "launchToken",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "refundVotes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseMilestone",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reportSuspiciousWallet",
    values: [AddressLike, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setLaunchFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startRefundVote",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "suspiciousReportCount",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tokens", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "unblacklistWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDevActivity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "usedEligibilityProofs",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawStuckBNB",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "ANTI_SNIPE_MAX_BNB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ANTI_SNIPE_SECONDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DAILY_SELL_CAP_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEV_STAKE_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ELIGIBILITY_PROOF_TTL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_DEV_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_LP_LOCK_DAYS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_UNIQUE_CONTRIBUTORS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_VESTING_DAYS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REPORT_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allTokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "antiSnipeContribs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blacklistWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "castRefundVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkLaunchSuccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimDevStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "contribute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "devLastActivity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "devLaunchHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "devRefundedLaunches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "devStakes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "devSuccessfulLaunches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDevLaunchHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDevStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSafetyScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokensPaginated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasContributed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasReported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "insurancePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBlacklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBlockedContributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isIronLockToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRefundVotePassed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "launchFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "launchToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reportSuspiciousWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLaunchFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startRefundVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "suspiciousReportCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unblacklistWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDevActivity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedEligibilityProofs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawStuckBNB",
    data: BytesLike
  ): Result;
}

export namespace BlacklistAddedEvent {
  export type InputTuple = [wallet: AddressLike, reason: string];
  export type OutputTuple = [wallet: string, reason: string];
  export interface OutputObject {
    wallet: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributedEvent {
  export type InputTuple = [
    token: AddressLike,
    contributor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    contributor: string,
    amount: bigint
  ];
  export interface OutputObject {
    token: string;
    contributor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DevActivityUpdatedEvent {
  export type InputTuple = [dev: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [dev: string, timestamp: bigint];
  export interface OutputObject {
    dev: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DevReputationUpdatedEvent {
  export type InputTuple = [
    dev: AddressLike,
    totalLaunches: BigNumberish,
    successful: BigNumberish,
    refunded: BigNumberish
  ];
  export type OutputTuple = [
    dev: string,
    totalLaunches: bigint,
    successful: bigint,
    refunded: bigint
  ];
  export interface OutputObject {
    dev: string;
    totalLaunches: bigint;
    successful: bigint;
    refunded: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DevStakeClaimedEvent {
  export type InputTuple = [dev: AddressLike, amount: BigNumberish];
  export type OutputTuple = [dev: string, amount: bigint];
  export interface OutputObject {
    dev: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DevStakeSlashedEvent {
  export type InputTuple = [dev: AddressLike, amount: BigNumberish];
  export type OutputTuple = [dev: string, amount: bigint];
  export interface OutputObject {
    dev: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LaunchFeeUpdatedEvent {
  export type InputTuple = [newFee: BigNumberish];
  export type OutputTuple = [newFee: bigint];
  export interface OutputObject {
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneReleasedEvent {
  export type InputTuple = [
    token: AddressLike,
    milestone: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, milestone: bigint, amount: bigint];
  export interface OutputObject {
    token: string;
    milestone: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundExecutedEvent {
  export type InputTuple = [token: AddressLike];
  export type OutputTuple = [token: string];
  export interface OutputObject {
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundVoteCastEvent {
  export type InputTuple = [
    token: AddressLike,
    voter: AddressLike,
    weight: BigNumberish
  ];
  export type OutputTuple = [token: string, voter: string, weight: bigint];
  export interface OutputObject {
    token: string;
    voter: string;
    weight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundVoteStartedEvent {
  export type InputTuple = [token: AddressLike];
  export type OutputTuple = [token: string];
  export interface OutputObject {
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StuckBNBWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenLaunchedEvent {
  export type InputTuple = [
    token: AddressLike,
    dev: AddressLike,
    name: string,
    symbol: string,
    totalSupply: BigNumberish,
    raiseCap: BigNumberish,
    lpLockDays: BigNumberish,
    vestingDays: BigNumberish,
    devAllocationBps: BigNumberish,
    safetyScore: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    dev: string,
    name: string,
    symbol: string,
    totalSupply: bigint,
    raiseCap: bigint,
    lpLockDays: bigint,
    vestingDays: bigint,
    devAllocationBps: bigint,
    safetyScore: bigint
  ];
  export interface OutputObject {
    token: string;
    dev: string;
    name: string;
    symbol: string;
    totalSupply: bigint;
    raiseCap: bigint;
    lpLockDays: bigint;
    vestingDays: bigint;
    devAllocationBps: bigint;
    safetyScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [newTreasury: AddressLike];
  export type OutputTuple = [newTreasury: string];
  export interface OutputObject {
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierUpdatedEvent {
  export type InputTuple = [newVerifier: AddressLike];
  export type OutputTuple = [newVerifier: string];
  export interface OutputObject {
    newVerifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletBlockedEvent {
  export type InputTuple = [token: AddressLike, wallet: AddressLike];
  export type OutputTuple = [token: string, wallet: string];
  export interface OutputObject {
    token: string;
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletReportedEvent {
  export type InputTuple = [
    token: AddressLike,
    reporter: AddressLike,
    suspiciousWallet: AddressLike,
    reason: string
  ];
  export type OutputTuple = [
    token: string,
    reporter: string,
    suspiciousWallet: string,
    reason: string
  ];
  export interface OutputObject {
    token: string;
    reporter: string;
    suspiciousWallet: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IronLockFactory extends BaseContract {
  connect(runner?: ContractRunner | null): IronLockFactory;
  waitForDeployment(): Promise<this>;

  interface: IronLockFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ANTI_SNIPE_MAX_BNB: TypedContractMethod<[], [bigint], "view">;

  ANTI_SNIPE_SECONDS: TypedContractMethod<[], [bigint], "view">;

  DAILY_SELL_CAP_BPS: TypedContractMethod<[], [bigint], "view">;

  DEV_STAKE_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  ELIGIBILITY_PROOF_TTL: TypedContractMethod<[], [bigint], "view">;

  MAX_DEV_BPS: TypedContractMethod<[], [bigint], "view">;

  MIN_LP_LOCK_DAYS: TypedContractMethod<[], [bigint], "view">;

  MIN_UNIQUE_CONTRIBUTORS: TypedContractMethod<[], [bigint], "view">;

  MIN_VESTING_DAYS: TypedContractMethod<[], [bigint], "view">;

  REPORT_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  allTokens: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  antiSnipeContribs: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  blacklistWallet: TypedContractMethod<
    [wallet: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  castRefundVote: TypedContractMethod<
    [tokenAddr: AddressLike, voteYes: boolean],
    [void],
    "nonpayable"
  >;

  checkLaunchSuccess: TypedContractMethod<
    [tokenAddr: AddressLike],
    [void],
    "nonpayable"
  >;

  claimDevStake: TypedContractMethod<
    [tokenAddr: AddressLike],
    [void],
    "nonpayable"
  >;

  claimRefund: TypedContractMethod<
    [tokenAddr: AddressLike],
    [void],
    "nonpayable"
  >;

  contribute: TypedContractMethod<[tokenAddr: AddressLike], [void], "payable">;

  contributions: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  devLastActivity: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  devLaunchHistory: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  devRefundedLaunches: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  devStakes: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  devSuccessfulLaunches: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  executeRefund: TypedContractMethod<
    [tokenAddr: AddressLike],
    [void],
    "nonpayable"
  >;

  getAllTokens: TypedContractMethod<[], [string[]], "view">;

  getDevLaunchHistory: TypedContractMethod<
    [dev_: AddressLike],
    [string[]],
    "view"
  >;

  getDevStats: TypedContractMethod<
    [dev_: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalLaunches: bigint;
        successful: bigint;
        refunded: bigint;
      }
    ],
    "view"
  >;

  getSafetyScore: TypedContractMethod<
    [tokenAddr: AddressLike],
    [bigint],
    "view"
  >;

  getTokensPaginated: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [[string[], bigint] & { result: string[]; total: bigint }],
    "view"
  >;

  hasContributed: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  hasReported: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: AddressLike],
    [boolean],
    "view"
  >;

  insurancePool: TypedContractMethod<[], [bigint], "view">;

  isBlacklisted: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isBlockedContributor: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isIronLockToken: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isRefundVotePassed: TypedContractMethod<
    [tokenAddr: AddressLike],
    [boolean],
    "view"
  >;

  launchFee: TypedContractMethod<[], [bigint], "view">;

  launchToken: TypedContractMethod<
    [
      name: string,
      symbol: string,
      totalSupply: BigNumberish,
      raiseCap: BigNumberish,
      lpLockDays: BigNumberish,
      vestingDays: BigNumberish,
      devAllocationBps: BigNumberish,
      eligibilityDeadline: BigNumberish,
      eligibilitySignature: BytesLike
    ],
    [string],
    "payable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  refundVotes: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        startTime: bigint;
        yesVotes: bigint;
        totalVotes: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;

  releaseMilestone: TypedContractMethod<
    [tokenAddr: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reportSuspiciousWallet: TypedContractMethod<
    [tokenAddr: AddressLike, suspiciousWallet: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  setLaunchFee: TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;

  setTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  setVerifier: TypedContractMethod<
    [_verifier: AddressLike],
    [void],
    "nonpayable"
  >;

  startRefundVote: TypedContractMethod<
    [tokenAddr: AddressLike],
    [void],
    "nonpayable"
  >;

  suspiciousReportCount: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  tokenCount: TypedContractMethod<[], [bigint], "view">;

  tokens: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint
      ] & {
        tokenAddress: string;
        dev: string;
        name: string;
        symbol: string;
        totalSupply: bigint;
        raiseCap: bigint;
        totalRaised: bigint;
        lpLockDays: bigint;
        vestingDays: bigint;
        devAllocationBps: bigint;
        launchTime: bigint;
        antiSnipeEnd: bigint;
        milestoneReleased: bigint;
        milestone1Time: bigint;
        milestone2Time: bigint;
        milestone3Time: bigint;
        safetyScore: bigint;
        active: boolean;
        refundVoteActive: boolean;
        maxContributionPerWallet: bigint;
        uniqueContributorCount: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  unblacklistWallet: TypedContractMethod<
    [wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  updateDevActivity: TypedContractMethod<[], [void], "nonpayable">;

  usedEligibilityProofs: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  verifier: TypedContractMethod<[], [string], "view">;

  withdrawStuckBNB: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ANTI_SNIPE_MAX_BNB"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ANTI_SNIPE_SECONDS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DAILY_SELL_CAP_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEV_STAKE_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ELIGIBILITY_PROOF_TTL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_DEV_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_LP_LOCK_DAYS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_UNIQUE_CONTRIBUTORS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_VESTING_DAYS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REPORT_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allTokens"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "antiSnipeContribs"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "blacklistWallet"
  ): TypedContractMethod<
    [wallet: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "castRefundVote"
  ): TypedContractMethod<
    [tokenAddr: AddressLike, voteYes: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkLaunchSuccess"
  ): TypedContractMethod<[tokenAddr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimDevStake"
  ): TypedContractMethod<[tokenAddr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[tokenAddr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "contribute"
  ): TypedContractMethod<[tokenAddr: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "contributions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "devLastActivity"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "devLaunchHistory"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "devRefundedLaunches"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "devStakes"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "devSuccessfulLaunches"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeRefund"
  ): TypedContractMethod<[tokenAddr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllTokens"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getDevLaunchHistory"
  ): TypedContractMethod<[dev_: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getDevStats"
  ): TypedContractMethod<
    [dev_: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalLaunches: bigint;
        successful: bigint;
        refunded: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSafetyScore"
  ): TypedContractMethod<[tokenAddr: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTokensPaginated"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [[string[], bigint] & { result: string[]; total: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasContributed"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasReported"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "insurancePool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isBlacklisted"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isBlockedContributor"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isIronLockToken"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRefundVotePassed"
  ): TypedContractMethod<[tokenAddr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "launchFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "launchToken"
  ): TypedContractMethod<
    [
      name: string,
      symbol: string,
      totalSupply: BigNumberish,
      raiseCap: BigNumberish,
      lpLockDays: BigNumberish,
      vestingDays: BigNumberish,
      devAllocationBps: BigNumberish,
      eligibilityDeadline: BigNumberish,
      eligibilitySignature: BytesLike
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refundVotes"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        startTime: bigint;
        yesVotes: bigint;
        totalVotes: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "releaseMilestone"
  ): TypedContractMethod<[tokenAddr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reportSuspiciousWallet"
  ): TypedContractMethod<
    [tokenAddr: AddressLike, suspiciousWallet: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setLaunchFee"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVerifier"
  ): TypedContractMethod<[_verifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startRefundVote"
  ): TypedContractMethod<[tokenAddr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "suspiciousReportCount"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "tokenCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokens"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint
      ] & {
        tokenAddress: string;
        dev: string;
        name: string;
        symbol: string;
        totalSupply: bigint;
        raiseCap: bigint;
        totalRaised: bigint;
        lpLockDays: bigint;
        vestingDays: bigint;
        devAllocationBps: bigint;
        launchTime: bigint;
        antiSnipeEnd: bigint;
        milestoneReleased: bigint;
        milestone1Time: bigint;
        milestone2Time: bigint;
        milestone3Time: bigint;
        safetyScore: bigint;
        active: boolean;
        refundVoteActive: boolean;
        maxContributionPerWallet: bigint;
        uniqueContributorCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unblacklistWallet"
  ): TypedContractMethod<[wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateDevActivity"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usedEligibilityProofs"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawStuckBNB"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "BlacklistAdded"
  ): TypedContractEvent<
    BlacklistAddedEvent.InputTuple,
    BlacklistAddedEvent.OutputTuple,
    BlacklistAddedEvent.OutputObject
  >;
  getEvent(
    key: "Contributed"
  ): TypedContractEvent<
    ContributedEvent.InputTuple,
    ContributedEvent.OutputTuple,
    ContributedEvent.OutputObject
  >;
  getEvent(
    key: "DevActivityUpdated"
  ): TypedContractEvent<
    DevActivityUpdatedEvent.InputTuple,
    DevActivityUpdatedEvent.OutputTuple,
    DevActivityUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DevReputationUpdated"
  ): TypedContractEvent<
    DevReputationUpdatedEvent.InputTuple,
    DevReputationUpdatedEvent.OutputTuple,
    DevReputationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DevStakeClaimed"
  ): TypedContractEvent<
    DevStakeClaimedEvent.InputTuple,
    DevStakeClaimedEvent.OutputTuple,
    DevStakeClaimedEvent.OutputObject
  >;
  getEvent(
    key: "DevStakeSlashed"
  ): TypedContractEvent<
    DevStakeSlashedEvent.InputTuple,
    DevStakeSlashedEvent.OutputTuple,
    DevStakeSlashedEvent.OutputObject
  >;
  getEvent(
    key: "LaunchFeeUpdated"
  ): TypedContractEvent<
    LaunchFeeUpdatedEvent.InputTuple,
    LaunchFeeUpdatedEvent.OutputTuple,
    LaunchFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneReleased"
  ): TypedContractEvent<
    MilestoneReleasedEvent.InputTuple,
    MilestoneReleasedEvent.OutputTuple,
    MilestoneReleasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RefundExecuted"
  ): TypedContractEvent<
    RefundExecutedEvent.InputTuple,
    RefundExecutedEvent.OutputTuple,
    RefundExecutedEvent.OutputObject
  >;
  getEvent(
    key: "RefundVoteCast"
  ): TypedContractEvent<
    RefundVoteCastEvent.InputTuple,
    RefundVoteCastEvent.OutputTuple,
    RefundVoteCastEvent.OutputObject
  >;
  getEvent(
    key: "RefundVoteStarted"
  ): TypedContractEvent<
    RefundVoteStartedEvent.InputTuple,
    RefundVoteStartedEvent.OutputTuple,
    RefundVoteStartedEvent.OutputObject
  >;
  getEvent(
    key: "StuckBNBWithdrawn"
  ): TypedContractEvent<
    StuckBNBWithdrawnEvent.InputTuple,
    StuckBNBWithdrawnEvent.OutputTuple,
    StuckBNBWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "TokenLaunched"
  ): TypedContractEvent<
    TokenLaunchedEvent.InputTuple,
    TokenLaunchedEvent.OutputTuple,
    TokenLaunchedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierUpdated"
  ): TypedContractEvent<
    VerifierUpdatedEvent.InputTuple,
    VerifierUpdatedEvent.OutputTuple,
    VerifierUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WalletBlocked"
  ): TypedContractEvent<
    WalletBlockedEvent.InputTuple,
    WalletBlockedEvent.OutputTuple,
    WalletBlockedEvent.OutputObject
  >;
  getEvent(
    key: "WalletReported"
  ): TypedContractEvent<
    WalletReportedEvent.InputTuple,
    WalletReportedEvent.OutputTuple,
    WalletReportedEvent.OutputObject
  >;

  filters: {
    "BlacklistAdded(address,string)": TypedContractEvent<
      BlacklistAddedEvent.InputTuple,
      BlacklistAddedEvent.OutputTuple,
      BlacklistAddedEvent.OutputObject
    >;
    BlacklistAdded: TypedContractEvent<
      BlacklistAddedEvent.InputTuple,
      BlacklistAddedEvent.OutputTuple,
      BlacklistAddedEvent.OutputObject
    >;

    "Contributed(address,address,uint256)": TypedContractEvent<
      ContributedEvent.InputTuple,
      ContributedEvent.OutputTuple,
      ContributedEvent.OutputObject
    >;
    Contributed: TypedContractEvent<
      ContributedEvent.InputTuple,
      ContributedEvent.OutputTuple,
      ContributedEvent.OutputObject
    >;

    "DevActivityUpdated(address,uint256)": TypedContractEvent<
      DevActivityUpdatedEvent.InputTuple,
      DevActivityUpdatedEvent.OutputTuple,
      DevActivityUpdatedEvent.OutputObject
    >;
    DevActivityUpdated: TypedContractEvent<
      DevActivityUpdatedEvent.InputTuple,
      DevActivityUpdatedEvent.OutputTuple,
      DevActivityUpdatedEvent.OutputObject
    >;

    "DevReputationUpdated(address,uint256,uint256,uint256)": TypedContractEvent<
      DevReputationUpdatedEvent.InputTuple,
      DevReputationUpdatedEvent.OutputTuple,
      DevReputationUpdatedEvent.OutputObject
    >;
    DevReputationUpdated: TypedContractEvent<
      DevReputationUpdatedEvent.InputTuple,
      DevReputationUpdatedEvent.OutputTuple,
      DevReputationUpdatedEvent.OutputObject
    >;

    "DevStakeClaimed(address,uint256)": TypedContractEvent<
      DevStakeClaimedEvent.InputTuple,
      DevStakeClaimedEvent.OutputTuple,
      DevStakeClaimedEvent.OutputObject
    >;
    DevStakeClaimed: TypedContractEvent<
      DevStakeClaimedEvent.InputTuple,
      DevStakeClaimedEvent.OutputTuple,
      DevStakeClaimedEvent.OutputObject
    >;

    "DevStakeSlashed(address,uint256)": TypedContractEvent<
      DevStakeSlashedEvent.InputTuple,
      DevStakeSlashedEvent.OutputTuple,
      DevStakeSlashedEvent.OutputObject
    >;
    DevStakeSlashed: TypedContractEvent<
      DevStakeSlashedEvent.InputTuple,
      DevStakeSlashedEvent.OutputTuple,
      DevStakeSlashedEvent.OutputObject
    >;

    "LaunchFeeUpdated(uint256)": TypedContractEvent<
      LaunchFeeUpdatedEvent.InputTuple,
      LaunchFeeUpdatedEvent.OutputTuple,
      LaunchFeeUpdatedEvent.OutputObject
    >;
    LaunchFeeUpdated: TypedContractEvent<
      LaunchFeeUpdatedEvent.InputTuple,
      LaunchFeeUpdatedEvent.OutputTuple,
      LaunchFeeUpdatedEvent.OutputObject
    >;

    "MilestoneReleased(address,uint8,uint256)": TypedContractEvent<
      MilestoneReleasedEvent.InputTuple,
      MilestoneReleasedEvent.OutputTuple,
      MilestoneReleasedEvent.OutputObject
    >;
    MilestoneReleased: TypedContractEvent<
      MilestoneReleasedEvent.InputTuple,
      MilestoneReleasedEvent.OutputTuple,
      MilestoneReleasedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RefundExecuted(address)": TypedContractEvent<
      RefundExecutedEvent.InputTuple,
      RefundExecutedEvent.OutputTuple,
      RefundExecutedEvent.OutputObject
    >;
    RefundExecuted: TypedContractEvent<
      RefundExecutedEvent.InputTuple,
      RefundExecutedEvent.OutputTuple,
      RefundExecutedEvent.OutputObject
    >;

    "RefundVoteCast(address,address,uint256)": TypedContractEvent<
      RefundVoteCastEvent.InputTuple,
      RefundVoteCastEvent.OutputTuple,
      RefundVoteCastEvent.OutputObject
    >;
    RefundVoteCast: TypedContractEvent<
      RefundVoteCastEvent.InputTuple,
      RefundVoteCastEvent.OutputTuple,
      RefundVoteCastEvent.OutputObject
    >;

    "RefundVoteStarted(address)": TypedContractEvent<
      RefundVoteStartedEvent.InputTuple,
      RefundVoteStartedEvent.OutputTuple,
      RefundVoteStartedEvent.OutputObject
    >;
    RefundVoteStarted: TypedContractEvent<
      RefundVoteStartedEvent.InputTuple,
      RefundVoteStartedEvent.OutputTuple,
      RefundVoteStartedEvent.OutputObject
    >;

    "StuckBNBWithdrawn(address,uint256)": TypedContractEvent<
      StuckBNBWithdrawnEvent.InputTuple,
      StuckBNBWithdrawnEvent.OutputTuple,
      StuckBNBWithdrawnEvent.OutputObject
    >;
    StuckBNBWithdrawn: TypedContractEvent<
      StuckBNBWithdrawnEvent.InputTuple,
      StuckBNBWithdrawnEvent.OutputTuple,
      StuckBNBWithdrawnEvent.OutputObject
    >;

    "TokenLaunched(address,address,string,string,uint256,uint256,uint256,uint256,uint16,uint8)": TypedContractEvent<
      TokenLaunchedEvent.InputTuple,
      TokenLaunchedEvent.OutputTuple,
      TokenLaunchedEvent.OutputObject
    >;
    TokenLaunched: TypedContractEvent<
      TokenLaunchedEvent.InputTuple,
      TokenLaunchedEvent.OutputTuple,
      TokenLaunchedEvent.OutputObject
    >;

    "TreasuryUpdated(address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;

    "VerifierUpdated(address)": TypedContractEvent<
      VerifierUpdatedEvent.InputTuple,
      VerifierUpdatedEvent.OutputTuple,
      VerifierUpdatedEvent.OutputObject
    >;
    VerifierUpdated: TypedContractEvent<
      VerifierUpdatedEvent.InputTuple,
      VerifierUpdatedEvent.OutputTuple,
      VerifierUpdatedEvent.OutputObject
    >;

    "WalletBlocked(address,address)": TypedContractEvent<
      WalletBlockedEvent.InputTuple,
      WalletBlockedEvent.OutputTuple,
      WalletBlockedEvent.OutputObject
    >;
    WalletBlocked: TypedContractEvent<
      WalletBlockedEvent.InputTuple,
      WalletBlockedEvent.OutputTuple,
      WalletBlockedEvent.OutputObject
    >;

    "WalletReported(address,address,address,string)": TypedContractEvent<
      WalletReportedEvent.InputTuple,
      WalletReportedEvent.OutputTuple,
      WalletReportedEvent.OutputObject
    >;
    WalletReported: TypedContractEvent<
      WalletReportedEvent.InputTuple,
      WalletReportedEvent.OutputTuple,
      WalletReportedEvent.OutputObject
    >;
  };
}
