/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  MockPancakeFactory,
  MockPancakeFactoryInterface,
} from "../../../../contracts/mocks/MockPancakeRouter.sol/MockPancakeFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_lp",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "getPair",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lpAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60a034606b57601f61018438819003918201601f19168301916001600160401b03831184841017606f57808492602094604052833981010312606b57516001600160a01b0381168103606b576080526040516101009081610084823960805181818160630152609b0152f35b5f80fd5b634e487b7160e01b5f52604160045260245ffdfe60808060405260043610156011575f80fd5b5f3560e01c9081639b4dc8cc14608b575063e6a4390514602f575f80fd5b3460875760403660031901126087576001600160a01b036004358181160360875760243581811603608757602090604051907f0000000000000000000000000000000000000000000000000000000000000000168152f35b5f80fd5b346087575f3660031901126087577f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03168152602090f3fea26469706673582212207bcf7a40cfd3e168168088ca041e2a96b3580d923b09cbf3956da17d4070070664736f6c63430008190033";

type MockPancakeFactoryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockPancakeFactoryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockPancakeFactory__factory extends ContractFactory {
  constructor(...args: MockPancakeFactoryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _lp: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_lp, overrides || {});
  }
  override deploy(
    _lp: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_lp, overrides || {}) as Promise<
      MockPancakeFactory & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockPancakeFactory__factory {
    return super.connect(runner) as MockPancakeFactory__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockPancakeFactoryInterface {
    return new Interface(_abi) as MockPancakeFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockPancakeFactory {
    return new Contract(address, _abi, runner) as unknown as MockPancakeFactory;
  }
}
