/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IIronLockFactoryInterface extends Interface {
  getFunction(nameOrSignature: "tokens"): FunctionFragment;

  encodeFunctionData(functionFragment: "tokens", values: [AddressLike]): string;

  decodeFunctionResult(functionFragment: "tokens", data: BytesLike): Result;
}

export interface IIronLockFactory extends BaseContract {
  connect(runner?: ContractRunner | null): IIronLockFactory;
  waitForDeployment(): Promise<this>;

  interface: IIronLockFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  tokens: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        tokenAddress: string;
        dev: string;
        name: string;
        symbol: string;
        totalSupply: bigint;
        raiseCap: bigint;
        totalRaised: bigint;
        lpLockDays: bigint;
        vestingDays: bigint;
        devAllocationBps: bigint;
        launchTime: bigint;
        antiSnipeEnd: bigint;
        milestoneReleased: bigint;
        milestone1Time: bigint;
        milestone2Time: bigint;
        milestone3Time: bigint;
        safetyScore: bigint;
        active: boolean;
        refundVoteActive: boolean;
        maxContributionPerWallet: bigint;
        uniqueContributorCount: bigint;
        liquidityBps: bigint;
        liquidityBNB: bigint;
        devBNB: bigint;
        softCap: bigint;
        presaleEnd: bigint;
        softCapHit: boolean;
        autoRefunded: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "tokens"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        tokenAddress: string;
        dev: string;
        name: string;
        symbol: string;
        totalSupply: bigint;
        raiseCap: bigint;
        totalRaised: bigint;
        lpLockDays: bigint;
        vestingDays: bigint;
        devAllocationBps: bigint;
        launchTime: bigint;
        antiSnipeEnd: bigint;
        milestoneReleased: bigint;
        milestone1Time: bigint;
        milestone2Time: bigint;
        milestone3Time: bigint;
        safetyScore: bigint;
        active: boolean;
        refundVoteActive: boolean;
        maxContributionPerWallet: bigint;
        uniqueContributorCount: bigint;
        liquidityBps: bigint;
        liquidityBNB: bigint;
        devBNB: bigint;
        softCap: bigint;
        presaleEnd: bigint;
        softCapHit: boolean;
        autoRefunded: boolean;
      }
    ],
    "view"
  >;

  filters: {};
}
