/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IIronLockFactory } from "./IIronLockFactory";
export type { IronLockMetadataRegistry } from "./IronLockMetadataRegistry";
