/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockPancakeRouter,
  MockPancakeRouterInterface,
} from "../../../contracts/mocks/MockPancakeRouter";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "WETH",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "addLiquidityETH",
    outputs: [
      {
        internalType: "uint256",
        name: "amountToken",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountETH",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "liquidity",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "factory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "getPair",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60c080604052346043573060805273bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c60a0526103149081610048823960805181610235015260a051816102760152f35b5f80fdfe60806040908082526004361015610014575f80fd5b5f3560e01c908163ad5c46481461026457508063c45a015514610221578063e6a43905146101a15763f305d7191461004a575f80fd5b60c036600319011261014e5761005e6102a5565b6001600160a01b0360843581811693929084900361014e5716908051916370a0823160e01b83528360048401526020938484602481855afa93841561019757908592915f95610163575b509060645f9392855194859384926323b872dd60e01b845260048401523060248401528860448401525af1801561015957610122575b503482029282840434148315171561010e57606093670de0b6b3a764000091835194855234908501520490820152f35b634e487b7160e01b5f52601160045260245ffd5b8381813d8311610152575b61013781836102bb565b8101031261014e57518015150361014e575f6100de565b5f80fd5b503d61012d565b82513d5f823e3d90fd5b838193949296503d8311610190575b61017c81836102bb565b8101031261014e57519284919060646100a8565b503d610172565b83513d5f823e3d90fd5b503461014e578060031936011261014e576101ba6102a5565b6001600160a01b036024358181160361014e57825160609290921b6001600160601b0319166020830190815260148352828401926001600160401b0384118185101761020d578360209552519020168152f35b634e487b7160e01b5f52604160045260245ffd5b503461014e575f36600319011261014e57517f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03168152602090f35b3461014e575f36600319011261014e577f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03168152602090f35b600435906001600160a01b038216820361014e57565b601f909101601f19168101906001600160401b0382119082101761020d5760405256fea2646970667358221220f86e23383fecd55e9e6278c2045936eecefbb04f273ced7c95d994669f0b73da64736f6c63430008190033";

type MockPancakeRouterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockPancakeRouterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockPancakeRouter__factory extends ContractFactory {
  constructor(...args: MockPancakeRouterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockPancakeRouter & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockPancakeRouter__factory {
    return super.connect(runner) as MockPancakeRouter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockPancakeRouterInterface {
    return new Interface(_abi) as MockPancakeRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockPancakeRouter {
    return new Contract(address, _abi, runner) as unknown as MockPancakeRouter;
  }
}
