/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockPancakeRouterSol from "./MockPancakeRouter.sol";
export type { mockPancakeRouterSol };
